name: robert-adina-wedding-photos
services:
- name: web
  source_dir: /
  git:
    repo: https://github.com/psilly-billy/upload_w
    branch: main
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: FOLDER_ID
    scope: RUN_TIME
    type: SECRET
  - key: SERVICE_ACCOUNT_KEY_JSON
    scope: RUN_TIME
    type: SECRET 